### ISSUE TITLE
Porque hacerlo facil si puede ser dificil :-)

### ISSUE THREAD

**Issue by agarzon** [fcoagz/pydolarvenezuela#1]
Echa una mirada a: 

https://exchangemonitor.net/ajax/widget-unique?country=ve&type=enparalelovzla

Servido en bandeja de plata, sin necesidad de usar xpath ni ningún otro parsing.... un lindo objeto JSON

... de nada  😂

**Comment by fcoagz** [comment]
Anteriormente de haber actualizado la librería habia encontrado el módulo en la página, para la obtención de los datos y pueda crear el widget. Pero el tiempo en que se demoraría en obtener los datos para cada unos de los monitores es tedioso, al realizar el scraping primero obtienes el contenido de la página y luego scrapeas los elementos que deseas obtener, por eso he realizado la API para la obtención de los datos más accesible para aquellos que tal solo realizar una petición GET, obtienes los datos de cada unos de los monitores

**Comment by fcoagz** [comment]
Otra cosa es que el módulo que has proporcionado no ofrece toda la información de la seccion de los bancos y algunos monitores (cuando anteriormente había encontrado el módulo)
