### ISSUE TITLE
Agregar la fecha de vigencia de los datos.

### ISSUE THREAD

**Issue by jochdev** [fcoagz/pydolarvenezuela#2]
Sería útil agregar a la respuesta de la API el dato "Fecha Valor" de la sección tasa de cambio oficial.

`<div class="pull-right dinpro center">Fecha Valor: <span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2024-05-14T00:00:00-04:00">Martes, 14 Mayo  2024</span></div>`

**Comment by fcoagz** [comment]
Buenos noches. De hecho lo está, pero en formato `yyyy/mm/dd`. 

```json
"last_update": "2024/05/14"
```

**Comment by jochdev** [comment]
sí, he verificado la información, gracias por esta herramienta
